from typing import Protocol

from app.models import Order


class OrderRepo(Protocol):
    def create(self, order: Order, items: list) -> Order: ...

    def list_by_session(self, session_id: int) -> list[Order]: ...

    def list_active_by_store(self, store_id: int, table_filter: int | None = None) -> list[Order]: ...

    def update_status(self, order_id: int, status: str) -> Order: ...

    def delete(self, order_id: int) -> None: ...

    def sum_total_by_table(self, table_id: int) -> int: ...
